version: 2

sources:
  - name: staging
    database: dtc-de-414113
    schema: trips_data_all

    tables:
      - name: green_trips_data_all_external_table
      - name: yellow_trips_data_all
